#pragma once
#define LEDS_CRICUMF 360 // must be divisible by BLADES
#define LEDS_PER_BLADE 360
#define BYTES_PER_LED 3
#define BLADES 5

#define TEENSY_IP "10.0.0.3"
#define TEENSY_PORT 8888
#define SUBNET_MASK "255.255.255.0"
#define GATEWAY "10.0.0.3"

#define SERVER_IP "10.0.0.2"
#define SERVER_PORT 12345

#define PREAMBLE_LENGTH 8
#define PREAMBLE_MAGIC_NUMBER 69
#define PREAMBLE_MAGIC_NUMBER_INDEX 0
#define PREAMBLE_FRAME_INDEX0 1
#define PREAMBLE_FRAME_INDEX1 2
#define PREAMBLE_FRAME_BUFFER_IN_INDEX0 3
#define PREAMBLE_FRAME_BUFFER_IN_INDEX1 4
